" about search
set ignorecase
set smartcase
set hlsearch
set incsearch

set background=dark
" about solarized theme
syntax enable

set t_Co=256
colorscheme molokai
"let g:solarized_termcolors=256
"colorscheme solarized

" No annoying sound
set noerrorbells
set novisualbell

" encoding,filetype
set encoding=utf8
set ffs=unix,dos,mac

" files,backups,undo
set nobackup
set nowb
set noswapfile

" about tab
set smarttab
set shiftwidth=4
set tabstop=4

" linebreak on 500 characters
set lbr
set tw=500
set number
set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

" about Vundle
set nocompatible

" shortcuts
map <F5> :call Compile()<CR>
map <F6> :call Debug() <CR>

func! Compile()
	if &filetype == "cpp"
		exec "w"
		exec "!g++ -std=c++14 -lpthread -g -Wall % -o %<"
		exec "! ./%<"
	elseif &filetype == "javascript"
		exec "w"
		exec "!node --harmony --use_strict %"
	elseif &filetype == "c"
		exec "w"
		exec "!gcc -g -Wall % -o %<"
		exec "! ./%<"
	elseif &filetype == "sh"
		exec "w"
		exec "!bash %"
	endif
endfunc
" %<
func! Debug() 
	if &filetype == "cpp"
		exec "!g++ -std=c++14 -lpthread -g -Wall % -o %<"
		exec "!cgdb %<"
	elseif &filetype == "c"
		exec "!gcc -g -Wall % -o %<"
		exec "! ./%<"
	endif
endfunc
